# Generated by Django 2.1.7 on 2019-06-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('razorpay_gateway', '0002_delete_temporarysecurityvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=500)),
                ('user_unique_id', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=30)),
                ('amount_debited', models.FloatField(max_length=20)),
                ('points_added', models.IntegerField()),
            ],
        ),
    ]
