# Generated by Django 2.1.7 on 2019-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_cart_item',
            field=models.IntegerField(default=0),
        ),
    ]
