# Generated by Django 2.1.7 on 2019-06-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points_available',
            field=models.FloatField(default=1.0, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='ok', max_length=50),
        ),
    ]
