# Generated by Django 2.1.7 on 2019-07-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_total_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_cart_item',
        ),
    ]
