# Generated by Django 2.1.7 on 2019-06-25 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190625_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=40, null=True, unique=True),
        ),
    ]
