# Generated by Django 2.1.7 on 2019-06-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='hotels_pics')),
                ('address', models.TextField()),
                ('contact_p_name', models.CharField(max_length=50)),
                ('contact_p_email', models.EmailField(blank=True, max_length=30)),
                ('contact_p_phone', models.IntegerField()),
                ('reward_ratio', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_t_hotel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_obtain', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservations',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.Guest'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.Hotels'),
        ),
    ]
