# Generated by Django 2.1.7 on 2019-07-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendpoints',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
