# Generated by Django 2.1.7 on 2019-06-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewarditem',
            name='item_id',
        ),
    ]
