# Generated by Django 2.1.7 on 2019-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_auto_20190610_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
