# Generated by Django 2.1.7 on 2019-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_remove_rewarditem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='item_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
