# Generated by Django 2.1.7 on 2019-07-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_tryguest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryGuest',
        ),
    ]
