# Generated by Django 2.1.7 on 2019-07-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_delete_tryguest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='v_t_hotel',
            field=models.FloatField(max_length=30),
        ),
    ]
