# Generated by Django 2.1.7 on 2019-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_auto_20190612_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='item_image',
            field=models.ImageField(default='default_image.jpg', upload_to='reward_item_pics'),
        ),
    ]
