# Generated by Django 2.1.7 on 2019-06-25 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_auto_20190625_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarditem',
            name='item_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=1000, unique=True),
        ),
    ]
