# Generated by Django 2.1.7 on 2019-06-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_rewarditem_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('points_required', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.Hotels')),
            ],
        ),
        migrations.AlterField(
            model_name='rewarditem',
            name='item_image',
            field=models.ImageField(default='default_image.png', upload_to='reward_item_pics'),
        ),
    ]
