# Generated by Django 2.1.7 on 2019-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_auto_20190724_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.CharField(default='Wed Jul 24 22:52:41 2019', max_length=50),
        ),
    ]
