# Generated by Django 2.1.7 on 2019-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_auto_20190613_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdeals',
            name='original_price',
            field=models.FloatField(default=111, max_length=10),
            preserve_default=False,
        ),
    ]
