# Generated by Django 2.1.7 on 2019-07-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_auto_20190724_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.CharField(default='Wed Jul 24 23:37:32 2019', max_length=50),
        ),
        migrations.AlterField(
            model_name='spendpoints',
            name='date',
            field=models.CharField(default='Wed Jul 24 23:37:32 2019', max_length=50),
        ),
    ]
