# Generated by Django 2.1.7 on 2019-06-17 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
