# Generated by Django 2.1.7 on 2019-06-17 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0009_reservations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spend', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.RewardItem')),
                ('special_deals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.SpecialDeals')),
            ],
        ),
        migrations.AlterField(
            model_name='reservations',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.Guest'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalty.Hotels'),
        ),
    ]
