# Generated by Django 2.1.7 on 2019-06-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0010_auto_20190617_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendpoints',
            name='points_spend',
        ),
    ]
