# Generated by Django 2.1.7 on 2019-06-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0011_remove_spendpoints_points_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendpoints',
            name='reward_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.RewardItem'),
        ),
        migrations.AlterField(
            model_name='spendpoints',
            name='special_deals',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.SpecialDeals'),
        ),
    ]
