# Generated by Django 2.1.7 on 2019-06-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0013_auto_20190617_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendpoints',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalty.Guest'),
        ),
    ]
